name: Ci workflow e2e

on:
  pull_request:
    paths:
      - '05-testing/**'

jobs:
  ci-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./05-testing/origin-front-admin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Tests e2e
        run: npm run test:e2e:ci
      - name: Upload screenshots when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./cypress/screenshots
      - name: Upload videos when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ./cypress/videos
